### ISSUE TITLE
missing test for host port and host binding env flags for qttasserver

### ISSUE THREAD

**Issue by jppiiroinen** [nomovok-opensource/cutedriver-examples#6]
There should be tests to cover the QTTASSERVER_HOST_BINDING and QTTASSERVER_HOST_PORT env flags.

**Comment by rasjani** [comment]
What level or framework  would those tests need to be ?

**Comment by jppiiroinen** [comment]
I am actually thinking this and writing something to have it there. Should have something after awhile.

Thinking something like a simple shell script which will launch qttasserver with the env flags and then runs tests. Then this will be done.

**Comment by jppiiroinen** [comment]
I should have had the tests done prior to the other pull request for agent_qt..

**Comment by jppiiroinen** [comment]
A pull request here:
https://github.com/nomovok-opensource/cutedriver-examples/pull/7

**Comment by jppiiroinen** [comment]
I ended up adding a minimal set of stuff. The ruby tests reads the environment flag QTTASSERVER_SUT for a custom sut value which has the new custom port and binding.

And there is a new "make check-alt" which will demonstrate the new environment variables in use.

**Comment by jppiiroinen** [comment]
I think that in general we should have some proper test suite for things like this, but this will also cover the added new feature. At least we will notice if the custom port stops working in the future.
